### ISSUE TITLE
Iphone OCR example

### ISSUE THREAD

**Issue by Rasia38956** [smart-mobile-software/ocrapiservice#1]
Is it possible to have a complete example of the OCR app ?

**Comment by bchessin** [comment]
I agree with @Rasia38956. Also you need to fix the bugs like no language parameter.

**Comment by poiuytrez** [comment]
We have updated today the example to a full example.
The Post request is working. However, we currently have an issue to select correctly the image on iOS 5. It will be fixed during the week.

**Comment by poiuytrez** [comment]
The image picker bug has been fixed

Commit :  9cc150a2b53971c3a1ae38b7ac14ec39192a91be
