### ISSUE TITLE
iOS No File Provided error- Back Again

### ISSUE THREAD

**Issue by sachinrot** [smart-mobile-software/ocrapiservice#10]
Hello There,
The issues is back again after one hour since i started consuming it.
I thought you fixed it for once and all ;)
Can you please fix this 
"HTTP/1.1 400 Bad Request No file provided"
Its both on your website and iOS code.
Thanks
Sachin

**Comment by poiuytrez** [comment]
We are on it. We are investigating.

**Comment by sachinrot** [comment]
Thank you, do you know when can we see it back in action? i am kind of working on that module in my app and this is holding me back a little.
Thanks a lot 
Sachin

**Comment by poiuytrez** [comment]
It is back. The problem was deeper than we though. Please contact me via the regular contact form to get a free small package as a compensation.

**Comment by sachinrot** [comment]
Its back and i hope this time its back for good :)
Thank a lot. not sure what is regular contact form to contact you but i guess its the one on your website.
Thanks
Sachin
