### ISSUE TITLE
iOS No File Provided error

### ISSUE THREAD

**Issue by sphuff** [smart-mobile-software/ocrapiservice#9]
Hi,

I am following the example that you put up and attempting to send a simple UIImage file. Everything appears to work correctly, but when I print out the data I receive, I am getting a 400 error. It reads:

Data received: HTTP/1.1 400 Bad Request

No file provided

My code is: (with key being my API key)
_ocrManager = [[OcrApiManager alloc] init];
_ocrManager.delegate = self;
UIImage *img = [UIImage imageNamed:@"quicksale_receipt"];
[_ocrManager postImage:img withApiKey:@"key" andLanguageCode:@"en"];

Any ideas? I am encountering the same problem when I try it in the website.

Thanks,

**Comment by interactivemartin** [comment]
Yes, the api looks down!. Can you fix this please????

**Comment by sachinrot** [comment]
Same problem here with iOS. does anybody got any solution on this?
Thanks
Sachin

**Comment by sachinrot** [comment]
do anyone have idea about when there API will be up?
Thanks
Sachin

**Comment by interactivemartin** [comment]
Problem is general, whatever you use, not only in iOS.

Can someone from support say something?

## 

---

_Martín Lombana_ / CEO & Founder
INTERACTIVE_MARTIN_  —  CREATIVE AGENCY

_OFFICE_ : +34 946 759 137  | MOBILE: +34 633 63 02 35
_WEB *: INTERACTIVEMARTIN.COM http://www.interactivemartin.com/
*FACEBOOK *: FACEBOOK.COM/INTERACTIVEMARTIN
http://facebook.com/interactivemartin
*TWITTER_: TWITTER.COM/INTMARTIN http://twitter.com/intmartin

**Comment by sachinrot** [comment]
i was planning my commercial app based on there API but how can i be sure about how reliable it is if this is the case?
im not sure if i should be asking this question here but what is the alternate API for same purpose if anyone has any idea?
will help me a lot..
Thanks
Sachin

**Comment by interactivemartin** [comment]
Us too. It's really bad if it is this way.

On Friday, July 10, 2015, sachinrot notifications@github.com wrote:

> i was planning my commercial app based on there API but how can i be sure
> about how reliable it is if this is the case?
> im not sure if i should be asking this question here but what is the
> alternate API for same purpose if anyone has any idea?
> will help me a lot..
> Thanks
> Sachin
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/smart-mobile-software/ocrapiservice/issues/9#issuecomment-120530399
> .

## 

---

_Martín Lombana_ / CEO & Founder
INTERACTIVE_MARTIN_  —  CREATIVE AGENCY

_OFFICE_ : +34 946 759 137  | MOBILE: +34 633 63 02 35
_WEB *: INTERACTIVEMARTIN.COM http://www.interactivemartin.com/
*FACEBOOK *: FACEBOOK.COM/INTERACTIVEMARTIN
http://facebook.com/interactivemartin
*TWITTER_: TWITTER.COM/INTMARTIN http://twitter.com/intmartin

**Comment by poiuytrez** [comment]
Hello guys, we are very sorry for the issue we had this weekend. Everything is now working properly. We have taken additional measure so it won't happen next time.

**Comment by sachinrot** [comment]
Thank you very much, this has resolved the problem and im able to test it now.
Thanks
Sachin

**Comment by sachinrot** [comment]
Hello There,
Seems like its back again.1 hour of use and im back where i started, its giving me File not provided error again both on website and iOS code.Can you please check this again.
Thanks 
Sachin

**Comment by poiuytrez** [comment]
It is back. The problem was deeper than we thought. Please contact me via the regular contact form to get a free small package as a compensation.
